### ISSUE TITLE
Version 1.0.2 does not contain \layouts\application.html.erb

### ISSUE THREAD

**Issue by atlasntefft** [dartmouth-dltg/aspace_analytics#3]
Greetings,

I just noticed that the 1.0.2 plugin does not contain the \public\views\layouts\application.html.erb that was present in the 1.0.1 version.
Is this an intended change?

Thanks!

**Comment by jdshaw** [comment]
Yep. v1.0.2 is compatible with AS v3.4.0 which includes the bit of code in the core views that warranted overriding that specific view. 

If you are using AS v3.3.1, continue to use the v1.0.1 release

**Comment by atlasntefft** [comment]
Thanks for the reply.  We have a customer who is reporting they are no longer getting telemetry from the new version.
I'm attaching what they're seeing and the contents of body_top.html.erb & layout_head.html.erb

Based on the readme, the noscript info should go into public/views/body_top.html.erb however we think it's in layout_head.html.erb on our end.  The funny thing is we didn't change the contents of those files during the update.

Would you be willing to take a look at what we have going on?

https://atlas-sys.sendsafely.com/receive/?packageCode=XclqjKvufe2SNphcam8GANgN36lfSNwiRk1llXz148s#keycode=vypb9FaHKVXOZ32JWNWGl29Ux985Aq_y_xxdSds8EtA

**Comment by jdshaw** [comment]
Took a quick look at the files you sent and it does look like the contents are reversed from where they should be. The tag manager script should be in layout_head and the noscript snippet should be in body_top.

Once updated, it should be pretty easy to verify that the contents are in the correct place by taking a peek at any PUI page source.

However, I'm not sure why (if the contents are where they were previously) that reversed order should be preventing the telemetry from being recorded since the noscript tag should not fire and the regular script should just fire a bit later than usual.

**Comment by jdshaw** [comment]
Apologies! Looks like I was too hasty in removing that view override. I *thought* it had made it to the core code, but not yet.

 I've reverted it and will be issuing a new release ASAP.

**Comment by atlasntefft** [comment]
Thanks, Josh!  I updated to the new 1.0.3 plugin successfully.  I also reserved the codes, as suggested, so things work as smoothly as possible.
